GET http://localhost:5000/user-service/test
Accept: application/json
token: {{token}}

###
GET http://localhost:5000/user-service/test
Accept: application/json

###
GET http://localhost:5000/user-service/user/hello
Accept: application/json

###
GET http://localhost:5000/user-service/user/count
Accept: application/json
token: {{token}}

###
POST http://localhost:5000/user-service/user/login
Content-Type: application/json

{
  "phone": "13951905171",
  "password": "123123"
}
> {%
 client.global.set("token",response.body.data.token);

 %}
###
POST http://localhost:5000/user-service/user/register
Content-Type: application/json

{
  "phone": "139519051712",
  "password": "123123"
}
###
GET http://localhost:5000/user-service/1
Accept: application/json
