GET http://localhost:8001/user-service/test
Accept: application/json

###
GET http://localhost:5000/user-service/test
Accept: application/json

###
GET http://localhost:5000/user-service/user/hello
Accept: application/json

###
GET http://localhost:5000/user-service/user/count
Accept: application/json

###
POST http://localhost:5000/user-service/user/login
Content-Type: application/json

{
  "phone": "13951905171",
  "password": "123123"
}
###
POST http://localhost:5000/user-service/user/register
Content-Type: application/json

{
  "phone": "13951905171",
  "password": "123123"
}
###