server:
  port: 5000
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        heart-beat-interval: 5000
        heart-beat-timeout: 15000
        namespace: dev
    gateway:
      discovery:
        locator:
          #          允许网关通过服务发现组件 找到其他微服务
          enabled: true
      routes:
        - id: route-user
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
        - id: route-content
          uri: lb://content-service
          predicates:
            - Path=/content-service/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*" # 允许请求来源
            allowCredentials: "true" # 允许携带认证信息
            allowedMethods: "*"   # 允许跨域的method， 默认为GET和OPTIONS，设置*为全部
            allowedHeaders: "*"   # 允许跨域请求里的head字段，设置*为全部
            maxAge: "3600" #跨域检测有效期 会发起一个OPTION请求



knife4j:
  # 聚合swagger文档
  gateway:
    enabled: true
    routes:
      - name: route-user
        # 真实子服务访问url地址-提供OpenAPI的文档
        url: /user-service/v3/api-docs?group=user
        service-name: user-service
        order: 2
      - name: route-content
        url: /content-service/v3/api-docs?group=content
        service-name: content-service
        order: 3
